application: pocketaccountant
version: 1
runtime: python
api_version: 1

handlers:
- url: /daily_email
  script: daily_email.py
  
- url: /twitterpull
  script: twitterpull.py
  
- url: /.*
  script: pocketaccountant.py
