application: pocketaccountant
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images
  
- url: /daily_email
  script: daily_email.py

- url: /firstdm
  script: firstdm.py
    
- url: /_ah/mail/twitter@pocketaccountant.appspotmail.com.*
  script: twitter.py 
  
- url: /.*
  script: pocketaccountant.py

inbound_services:
- mail